#!/bin/bash
export PYTHONPATH=${PYTHONPATH}:/src/jupyterhub:/src/jupyterhub-custom

USERNAME=jovyan

if [[ -n ${K8SMGRHDFCLOUD_JUPYTERHUB_USER_PASS} ]]; then
  export K8SMGRHDFCLOUD_JUPYTERHUB_USERNAME=${K8SMGRHDFCLOUD_JUPYTERHUB_USERNAME:-jupyterhub}
  export K8SMGRHDFCLOUD_AUTHENTICATION_TOKEN=${K8SMGRHDFCLOUD_AUTHENTICATION_TOKEN:-"Basic $(echo -n "${K8SMGRHDFCLOUD_JUPYTERHUB_USERNAME}:${K8SMGRHDFCLOUD_JUPYTERHUB_USER_PASS}" | base64 -w 0)"}
fi

if [[ -n ${UNICOREMGR_JUPYTERHUB_USER_PASS} ]]; then
  export UNICOREMGR_JUPYTERHUB_USERNAME=${UNICOREMGR_JUPYTERHUB_USERNAME:-jupyterhub}
  export UNICOREMGR_AUTHENTICATION_TOKEN=${UNICOREMGR_AUTHENTICATION_TOKEN:-"Basic $(echo -n "${UNICOREMGR_JUPYTERHUB_USERNAME}:${UNICOREMGR_JUPYTERHUB_USER_PASS}" | base64 -w 0)"}
fi

if [[ -n ${TUNNEL_JUPYTERHUB_USER_PASS} ]]; then
  export TUNNEL_JUPYTERHUB_USERNAME=${TUNNEL_JUPYTERHUB_USERNAME:-jupyterhub}
  export TUNNEL_AUTHENTICATION_TOKEN=${TUNNEL_AUTHENTICATION_TOKEN:-"Basic $(echo -n "${TUNNEL_JUPYTERHUB_USERNAME}:${TUNNEL_JUPYTERHUB_USER_PASS}" | base64 -w 0)"}
fi

if [[ -d /mnt/shared-data/tmp-internal-ssl ]]; then
  rm -rf /mnt/shared-data/tmp-internal-ssl/*
fi

/usr/bin/jupyterhub ${@}
