# Generated by Django 3.2.12 on 2022-04-04 08:46
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ServicesModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("servername", models.TextField(verbose_name="servername")),
                ("start_date", models.DateTimeField(auto_now_add=True)),
                (
                    "user_options",
                    models.JSONField(default=dict, verbose_name="user_options"),
                ),
                ("jhub_user_id", models.IntegerField(verbose_name="jhub_user_id")),
                (
                    "jhub_credential",
                    models.TextField(
                        default="jupyterhub", verbose_name="jhub_credential"
                    ),
                ),
                ("stop_pending", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="UserModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("jhub_user_id", models.IntegerField(verbose_name="jhub_user_id")),
                (
                    "jhub_credential",
                    models.TextField(
                        default="jupyterhub", verbose_name="jhub_credential"
                    ),
                ),
            ],
        ),
    ]
