# Generated by Django 3.2.16 on 2022-12-05 13:19
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_servicesmodel_start_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserJobsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_ports",
                    models.JSONField(default=dict, verbose_name="target_ports"),
                ),
                (
                    "jhub_credential",
                    models.TextField(
                        default="jupyterhub", verbose_name="jhub_credential"
                    ),
                ),
                ("suffix", models.TextField(verbose_name="suffix")),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="services.servicesmodel",
                    ),
                ),
            ],
        ),
    ]
