# Generated by Django 3.2.16 on 2022-12-07 10:05
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0003_userjobsmodel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userjobsmodel",
            name="target_ports",
        ),
        migrations.AddField(
            model_name="userjobsmodel",
            name="hostname",
            field=models.TextField(default="", verbose_name="hostname"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userjobsmodel",
            name="target_node",
            field=models.TextField(default="", verbose_name="target_node"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userjobsmodel",
            name="used_ports",
            field=models.JSONField(default=dict, verbose_name="used_ports"),
        ),
    ]
