# Generated by Django 3.2.16 on 2022-12-07 10:55
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0004_auto_20221207_1005"),
    ]

    operations = [
        migrations.AddField(
            model_name="userjobsmodel",
            name="userjobs",
            field=models.TextField(default="a", verbose_name="userjobs"),
            preserve_default=False,
        ),
    ]
