# Generated by Django 3.2.16 on 2023-01-10 15:15
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0005_userjobsmodel_userjobs"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userjobsmodel",
            name="suffix",
        ),
    ]
