# Generated by Django 3.2.16 on 2023-01-10 15:27
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0006_remove_userjobsmodel_suffix"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userjobsmodel",
            name="userjobs",
        ),
        migrations.AlterField(
            model_name="userjobsmodel",
            name="service",
            field=models.TextField(verbose_name="userjobs"),
        ),
    ]
