# Generated by Django 3.2.12 on 2022-03-10 08:16
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HandlerModel",
            fields=[
                (
                    "handler",
                    models.TextField(
                        primary_key=True, serialize=False, verbose_name="handler"
                    ),
                ),
                ("configuration", models.JSONField(verbose_name="configuration")),
            ],
        ),
    ]
