apiVersion: v1
kind: ServiceAccount
metadata:
  name: svc-acc-k8smgr-devel
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-role-k8smgr-devel
rules:
- apiGroups: [""]
  resources: ["events"]
  verbs: ["list"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["create", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["create", "delete"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "delete"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["create", "delete"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create", "delete", "get", "list"]
- apiGroups: [""]
  resources: ["pods/mnt"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-role-binding-k8smgr-devel
subjects:
- kind: ServiceAccount
  name: svc-acc-k8smgr-devel
  namespace: <NAMESPACE>
roleRef:
  kind: ClusterRole
  name: cluster-role-k8smgr-devel
  apiGroup: rbac.authorization.k8s.io
